{{range .Values.certificates }}
---
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: {{ include "ssl.fullname" $ }}-{{ required "Name is required for secret" .name }}
  labels:
    {{- include "ssl.labels" $ | nindent 4 }}
data:
  tls.crt: {{ required (printf "Certificate is required for secret: %s" .name) .certificate }}
  tls.key: {{ required (printf "Private key is required for secret: %s" .name) .privateKey }}
{{- end }}
