{{ range .Values.services }}
---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "api-keys.fullname" $ }}-{{ required "Missing name for service" .name }}"
  labels:
    {{- include "api-keys.labels" $ | nindent 4 }}
data:
  key: {{ required (printf "Missing api key for service: %s" .name) .apiKey }}
{{- end }}