apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "token-keys.fullname" $ }}"
  labels:
    {{- include "token-keys.labels" $ | nindent 4 }}
data:
  private-key: {{ required "Access token private key required" .Values.privateKey }}
  public-key: {{ required "Access token public key required" .Values.publicKey }}
