/**
 * Phillips
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Phillips);
  }
}(this, function(expect, Phillips) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Phillips.ControlLightResponseTime();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ControlLightResponseTime', function() {
    it('should create an instance of ControlLightResponseTime', function() {
      // uncomment below and update the code to test ControlLightResponseTime
      //var instane = new Phillips.ControlLightResponseTime();
      //expect(instance).to.be.a(Phillips.ControlLightResponseTime);
    });

    it('should have the property day (base name: "day")', function() {
      // uncomment below and update the code to test the property day
      //var instance = new Phillips.ControlLightResponseTime();
      //expect(instance).to.be();
    });

    it('should have the property month (base name: "month")', function() {
      // uncomment below and update the code to test the property month
      //var instance = new Phillips.ControlLightResponseTime();
      //expect(instance).to.be();
    });

    it('should have the property year (base name: "year")', function() {
      // uncomment below and update the code to test the property year
      //var instance = new Phillips.ControlLightResponseTime();
      //expect(instance).to.be();
    });

    it('should have the property hour (base name: "hour")', function() {
      // uncomment below and update the code to test the property hour
      //var instance = new Phillips.ControlLightResponseTime();
      //expect(instance).to.be();
    });

    it('should have the property minute (base name: "minute")', function() {
      // uncomment below and update the code to test the property minute
      //var instance = new Phillips.ControlLightResponseTime();
      //expect(instance).to.be();
    });

    it('should have the property second (base name: "second")', function() {
      // uncomment below and update the code to test the property second
      //var instance = new Phillips.ControlLightResponseTime();
      //expect(instance).to.be();
    });

  });

}));
