apiVersion: v2
name: secrets
description: A Helm chart for Kubernetes
type: application
version: 0.1.0

dependencies:
  - name: db-users
    repository: "file://./charts/db-users"
    version: 0.1.0
  - name: api-keys
    repository: "file://./charts/api-keys"
    version: 0.1.0
  - name: token-keys
    repository: "file://./charts/token-keys"
    version: 0.1.0
  - name: ssl
    repository: "file://./charts/ssl"
    version: 0.1.0