apiVersion: v2
name: api-gateway
description: A Helm chart for Kubernetes
type: application
version: 0.1.0

dependencies:
  - name: gateway
    repository: "file://./charts/gateway"
    version: 0.1.0
    alias: internal-gateway
  - name: gateway
    repository: "file://./charts/gateway"
    version: 0.1.0
    alias: external-gateway