/**
 * Phillips
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import BadRequestResponse from '../model/BadRequestResponse';
import ControlLightRequest from '../model/ControlLightRequest';
import ControlLightResponse from '../model/ControlLightResponse';

/**
* Default service.
* @module api/DefaultApi
* @version 1.0
*/
export default class DefaultApi {

    /**
    * Constructs a new DefaultApi. 
    * @alias module:api/DefaultApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * Set the state of a certain light bulb
     * @param {module:model/ControlLightRequest} controlLightRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/ControlLightResponse} and HTTP response
     */
    controlLightWithHttpInfo(controlLightRequest) {
      let postBody = controlLightRequest;
      // verify the required parameter 'controlLightRequest' is set
      if (controlLightRequest === undefined || controlLightRequest === null) {
        throw new Error("Missing the required parameter 'controlLightRequest' when calling controlLight");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = ControlLightResponse;
      return this.apiClient.callApi(
        '/state', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Set the state of a certain light bulb
     * @param {module:model/ControlLightRequest} controlLightRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/ControlLightResponse}
     */
    controlLight(controlLightRequest) {
      return this.controlLightWithHttpInfo(controlLightRequest)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
