/**
 * Phillips
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ControlLightResponseTime from './ControlLightResponseTime';

/**
 * The ControlLightResponse model module.
 * @module model/ControlLightResponse
 * @version 1.0
 */
class ControlLightResponse {
    /**
     * Constructs a new <code>ControlLightResponse</code>.
     * @alias module:model/ControlLightResponse
     */
    constructor() { 
        
        ControlLightResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ControlLightResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ControlLightResponse} obj Optional instance to populate.
     * @return {module:model/ControlLightResponse} The populated <code>ControlLightResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ControlLightResponse();

            if (data.hasOwnProperty('success')) {
                obj['success'] = ApiClient.convertToType(data['success'], 'Boolean');
            }
            if (data.hasOwnProperty('time')) {
                obj['time'] = ControlLightResponseTime.constructFromObject(data['time']);
            }
        }
        return obj;
    }


}

/**
 * @member {Boolean} success
 */
ControlLightResponse.prototype['success'] = undefined;

/**
 * @member {module:model/ControlLightResponseTime} time
 */
ControlLightResponse.prototype['time'] = undefined;






export default ControlLightResponse;

