# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]
    paths:
      - "Backend/User\ Service/**"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: Build User Service
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Move to auth service folder
        run: cd Backend/User\ Service
      
      - name: Install dev dependencies
        run: npm install --only=dev
      
      - name: Build typescript
        run: npm run build
      
      - name: Build docker
        run: npm run docker-build
      
      - name: Push docker
        run: npm run docker-push
        
      - name: Create fresh helm chart
        run: npm run helm-build
      
      - name: Push chart to chart repository
        run: npm run helm-push
