name: Docker Infrastructure

on:
  workflow_dispatch:

  push:
    branches: [main]
    paths:
      - "Docker\ Infrastructure/**"

jobs:
  build:
    name: Build Database
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "./main/Docker\ Infrastructure/database"

    steps:
      # Checkout main branch
      - name: Checkout main branch
        uses: actions/checkout@v2
        with:
          path: main

      # Build docker image
      - name: Build docker
        run: sh docker-build.sh

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push docker
        run: sh docker-push.sh