name: Helm Infrastructure

on:
  workflow_dispatch:

  push:
    branches: [main]
    paths:
      - "Helm\ Infrastructure/**"

jobs:
  build:
    name: Build Helm Infrastructure
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "./main/Helm\ Infrastructure"

    steps:
      # Checkout main branch
      - name: Checkout main branch
        uses: actions/checkout@v2
        with:
          path: main

      # Checkout chart repo
      - name: Checkout chart-repo
        uses: actions/checkout@v2
        with:
          ref: 'chart-repo'
          path: chart-repo

      - name: Create helm charts
        run: |
          for dirname in `find . -mindepth 1 -maxdepth 1 -type d`
          do
            helm package $dirname -d $GITHUB_WORKSPACE/chart-repo
            helm repo index $GITHUB_WORKSPACE/chart-repo --url https://mauriceackel.github.io/CKDAC
          done

      # Push to chart repo
      - name: Push to chart-repo
        run: |
          cd $GITHUB_WORKSPACE/chart-repo
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Updated chart repository"
          COUNTER=0
          while [[ $(git push | echo $?) && $COUNTER -lt 3 ]]; do
            git reset HEAD~1
            git checkout index.yaml
            git stash
            git pull
            git checkout stash -- .
            helm repo index $GITHUB_WORKSPACE/chart-repo --url https://mauriceackel.github.io/CKDAC
            git add .
            git commit -m "Updated chart repository"
            ((COUNTER=COUNTER+1))
          done;
