# This is a basic workflow to help you get started with Actions

name: Adapter Service

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [main]
    paths:
      - "Backend/Adapter\ Service/**"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: Build Adapter Service
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "./Backend/Adapter\ Service"

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build typescript
        run: npm run build

      - name: Build docker
        run: npm run docker-build

      - name: Push docker
        run: npm run docker-push

      - name: Create fresh helm chart
        run: npm run helm-build

      - name: Push chart to chart repository
        run: npm run helm-push
