name: Adapter Service

on:
  workflow_dispatch:
  
  push:
    branches: [main]
    paths:
      - "Backend/Adapter\ Service/**"

jobs:
  build:
    name: Build Adapter Service
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "./Backend/Adapter\ Service"

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build typescript
        run: npm run build

      - name: Build docker
        run: npm run docker-build

      - name: Push docker
        run: npm run docker-push

      - name: Create fresh helm chart
        run: npm run helm-build

      - name: Push chart to chart repository
        run: npm run helm-push
